version: "2"

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ".:/app"
    depends_on:
      - "db"
    command: "mvn spring-boot:run"
  db:
    image: "postgres:latest"
    ports:
      - "5432:5432"
