version: '2'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ".:/work"
    depends_on:
      - "db"
  db:
    image: "postgres:latest"
    ports:
      - "5432:5432"
